= Asciidoctor Maven Plugin changelog
:uri-asciidoctor: http://asciidoctor.org
:uri-asciidoc: {uri-asciidoctor}/docs/what-is-asciidoc
:uri-repo: https://github.com/asciidoctor/asciidoctor-maven-plugin
:icons: font
:star: icon:star[role=red]
ifndef::icons[]
:star: &#9733;
endif::[]

This document provides a high-level view of the changes introduced on Asciidoctor Maven Plugin by release.
For a detailed view of what has changed, refer to the {uri-repo}/commits/main[commit history] on GitHub.

== Unreleased


== v3.1.1 (2024-11-14)

Improvements (for all modules)::

  * Use Maven Eclipse Sisu to inject components (allowed refactors to increase code re-use) (#945)
  * Centralize Maven4 configurations in a profile in the parent (#945)

Bug Fixes (Site Modules)::

  * Fix resolution of baseDir for Doxia modules (#968)

Improvements (Site Modules)::

  * Unify loggers initialization to be static (#971)

Build / Infrastructure::

  * Bump Maven Wrapper to v3.9.9 (#978)

== v3.1.0 (2024-10-30)

Bug Fixes::

  * Fix open IMG tags in parser-doxia-module (#783)
  * Fix naming in Asciidoctor Converter Doxia Module pom (#934)
  * Fix empty table generating <table> element (asciidoctor-parser-doxia-module) (#938)

Improvements::

  * Added support for AsciidoctorJ v3.0.0 (#651)
  * Add compatibility with maven-site-plugin v3.20.0 and Doxia v2.0.0 (#933)
  * Add support for code blocks titles (asciidoctor-parser-doxia-module) (#935)
  * Refactor AST traversal method (asciidoctor-parser-doxia-module) (#944)
  * Empty titles in document or empty literals no longer generate <h1> or <pre> in asciidoctor-parser-doxia-module (#944)
  * Sections are now wrapped in <div> in (asciidoctor-parser-doxia-module) (#944)
  * Add support for inline and Example blocks (asciidoctor-parser-doxia-module) (#938)
  * Add support for captioned titles in appendixes, tables, listing, figure, and examples (asciidoctor-parser-doxia-module) (#749)
  * Add INFO message to site modules showing the filename in case of issues (#323)

Build / Infrastructure::

  * Fix javadoc check flake in CI (#814)
  * Bump AsciidoctorJ to v3.0.0 (#651)

== v3.0.0 (2024-02-14)

Bug Fixes::

  * Fix default value for eruby which caused a fail when using erb templates (#610)
  * Fix maven properties not being injected as attributes during site conversion (#656)
  * Remove Java 'requires open access' module warning in modern Java versions with JRuby v9.4.5.0 (#553)
  * Fix breadcrumbs not showing the document title in maven-site pages (#763)
  * Fix resource copy in multi-module project (#838)

Improvements::

  * Split plugin and site integration in sub-modules: asciidoctor-maven-plugin and asciidoctor-doxia-module (#595)
  * Add 'asciidoc' as valid file extension in AsciidoctorDoxiaParserModule (#595)
  * Fix throwing an exception when registering a non Extension (#596)
  * Reimplement resource copy using 'plexus.util.DirectorScanner' instead of 'maven-filtering' to reduce dependencies and build time (#597)
  * Replace deprecated 'headerFooter' by 'standalone' in configuration (#649)
  * Remove internal use of 'destinationDir' AsciidoctorJ method (#650)
  * Upgrade Asciidoctorj to v2.5.11 (#688) and jRuby to v9.4.5.0 (#665)
  * Improve warning message when destination file is going to be replaced (#728)
  * Added `.editorconfig` file to facilitate code formatting (#760)

Build / Infrastructure::

  * Fix maven-source-plugin configuration for releases (#644)
  * Set Java 11 as minimal version (remove Java8 support) (#652)
  * Use Maven v3.9.5 in CI and wrapper (#662)
  * Add Java 21 to CI (#664)
  * Bump Doxia to v1.11.1 and maven-site-plugin in IT to 3.12.0 (#579)
  * Upgrade build related Maven plugins to the latest versions (#606)
  * Set minimal maven version to 3.8.5 (#607)
  * Bump GH 'checkout' and 'setup-java' to v3 & delete unused TravisCI configuration (#627)
  * Bump plugins versions & set CI Maven to v3.9.1 (#629)
  * Add Maven matrix testing + define Maven compatibility policy (#632)
  * Bump build related Maven plugins to the latest versions (#635)
  * Remove use of deprecated 'parent.version' Maven property (#606)
  * Add Dependabot to automate dependency management (#669)
  * Improvements to dependency management (#690)
  * Test Javadoc generation in CI (#690)
  * Fix maven-deploy-plugin and prerequisites Maven warnings (#709)
  * Use latest maven-plugin-tools and remove Dependabot exclusion (CI test ensure backward compatibility) (#717)
  * Use latest Maven Doxia and remove Dependabot exclusion (CI test ensure backward compatibility) (#719)
  * Use latest Maven and remove Dependabot exclusion (CI test ensure backward compatibility) (#722)
  * Test artifact's signature with Maven in CI (#736)
  * Automate release using GH Actions (#141)
  * Ensure Mojos use correct default values in unit tests (#609)
  * Replace use of reflection by direct JavaExtensionRegistry calls to register extensions (#596)

Documentation::

  * Fix absolute path in usage example and AsciiDoc references in docs (https://github.com/MarkusTiede[@MarkusTiede])(#592)
  * Add v3.x.x migration guide (#598)
