= Asciidoctor Maven Plugin changelog
:uri-asciidoctor: http://asciidoctor.org
:uri-asciidoc: {uri-asciidoctor}/docs/what-is-asciidoc
:uri-repo: https://github.com/asciidoctor/asciidoctor-maven-plugin
:icons: font
:star: icon:star[role=red]
ifndef::icons[]
:star: &#9733;
endif::[]

This document provides a high-level view of the changes introduced on Asciidoctor Maven Plugin by release.
For a detailed view of what has changed, refer to the {uri-repo}/commits/main[commit history] on GitHub.

== Unreleased

Documentation::

  * Migrate docs (README) to Antora site and publish them in gh-pages (#498)
  * Remove ambiguity in usage of maven properties docs (#507)
  * Add ID to 'attributes' description, to be able to generate direct url from other docs (#509)
  * Fix broken links to extension api documentation (https://github.com/djarnis73[@djarnis73]) (#523)
  * Remove local antora site generator stuff (https://github.com/uniqueck[@uniqueck]) (#529)

Build / Infrastructure::
  * Upgrade tests to JUni5 (#521)
  * Rename main branch (#524)
  * Set maven wrapper to use maven v3.8.1 (#525)
  * Upgrade Asciidoctorj to v2.4.3 and jRuby to v9.2.14.0 (#526)
  * Upgrade Asciidoctorj to v2.5.0 and jRuby to v9.2.17.0 (#531)
  * Upgrade Asciidoctorj to v2.5.1 (#534)

Maintenance::

  * Upgrade `netty-codec-http` to 4.1.29.Final and refactor `AsciidoctorHttpServer` (#511)
  * Rewrite `AsciidoctorMojoTest` to Java to make it more approachable (#512)
  * Rewrite `AsciidoctorMojoLogHandlerTest` to Java to make it more approachable (#514)
  * Rewrite `AsciidoctorMojoExtensionsTest` to Java to make it more approachable (#515)
  * Rewrite `AsciidoctorHttpMojoTest` to Java to make it more approachable (#516)
  * Rewrite `AsciidoctorZipMojoTest` to Java to make it more approachable (#518)
  * Rewrite `AsciidoctorDoxiaParserTest` to Java + remove Groovy & Spock configurations (#519)
  * Replace usage of internal Asciidoctorj `DirectoryWalker` with Java NIO API (https://github.com/stdll[@stdll]) (#532)

== v2.1.0 (2020-09-15)

Improvements::

  * Inject Maven properties as attributes in `process-asciidoc` mojo (#459)
  * Make `auto-refresh` (and `http` by inheritance) only convert modified and created sources (#474)
  * Make `auto-refresh` only copy modified and created resources + taking into consideration <resources> options (#478)
  * Make `auto-refresh` ignore docInfo files to avoid copying them into output (#480)
  * Add official support for `http` mojo with life preview and refresh of html output (#483)

Bug Fixes::

  * Remove Maven components from plugin descriptor (#450)
  * Remove unnecessary maven's @Parameter configuration from ExtensionConfiguration, Synchronization and Resources (#461)
  * Remove unused BuildContext from AsciidoctorMojo (#462)
  * Remove unnecessary required configuration from mojo parameters (#463)
  * Prevent sources from being converted twice in http mojo (#469)
  * Remove synchronization property from mojo (#471)

Documentation::

  * Add reference to v2-migration-guide in README for better findability (#445)
  * Fix broken link to V2 migration guide (https://github.com/ge0ffrey[@ge0ffrey]) (#446)
  * Add GitHub's PR and issue templates (#465)
  * Add `auto-refresh` mojo documentation (#466)
  * Add copyright notice to README and remove unnecessary license header from sources (#482)

Build / Infrastructure::

  * Updated maven-release-plugin version (3.0.0-M1) and POM scm configuration to simplify release process
  * Adds GitHub Actions build for Linux, Windows, MacOS and Java 8, 11 (#452, #453)
  * Simplify TravisCI and AppVeyor to run Java 8 and 11 only (#460)
  * Upgrade Maven from v3.5.0 to 3.6.3 in AppVeyor (#460)
  * Updated jacoco-maven-plugin version from v0.8.2 to 0.8.5 (#479)
  * Use maven-javadoc-plugin version defined in `pluginManagement` + update to v3.2.0 (#481)
  * Add Maven Wrapper to project and CI builds (#484)
  * Upgrade Asciidoctorj to 2.4.1 and jRuby to 9.2.13.0 (#486)
