= Asciidoctor Maven 插件
:translators: D瓜哥
ifdef::env-github[Translated by: {translators}]
// Metadata
:release-version: 1.5.2
// Settings
:page-layout: base
:idprefix:
:idseparator: -
:toc: preamble
ifdef::env-github[:badges:]
// URIs
:project-repo: asciidoctor/asciidoctor-maven-plugin
:uri-asciidoc: http://asciidoc.org
:uri-asciidoctor: http://asciidoctor.org
:uri-examples: https://github.com/asciidoctor/asciidoctor-maven-examples
:uri-maven: http://maven.apache.org

ifdef::badges[]
image:https://ci.appveyor.com/api/projects/status/chebmu91f08dlmsc/branch/master?svg=true["Build Status (AppVeyor)", link="https://ci.appveyor.com/project/asciidoctor/asciidoctor-maven-plugin"]
image:http://img.shields.io/travis/asciidoctor/asciidoctor-maven-plugin/master.svg["Build Status (Travis CI)", link="https://travis-ci.org/asciidoctor/asciidoctor-maven-plugin"]
image:http://img.shields.io/coveralls/{project-repo}/master.svg["Coverage Status", link="https://coveralls.io/r/{project-repo}?branch=master"]
image:https://maven-badges.herokuapp.com/maven-central/org.asciidoctor/asciidoctor-maven-plugin/badge.svg["Maven Central",link="https://maven-badges.herokuapp.com/maven-central/org.asciidoctor/asciidoctor-maven-plugin"]
endif::[]

Asciidoctor Maven 插件是一种官方支持的方式，它可以在 {uri-maven}[Apache Maven] 构建过程中使用 {uri-asciidoctor}[Asciidoctor] 转化你的 {uri-asciidoc}[AsciiDoc]  文档。

[[installation]]
== Installation

作为一个典型的 Maven 插件，可以很容易地在 POM 文件的 `<plugins>` 部分声明使用：

[source,xml,subs=attributes+]
.pom.xml 中的插件声明
----
<plugins>
    <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>{release-version}</version> <!--1-->
        ...
    </plugin>
</plugins>
----
<1> 这个插件的版本紧跟 Asciidoctor 的版本，你可以使用任意喜欢的 Asciidoctor 版本。

[[usage]]
== 使用

[source,xml]
.执行配置
----
<plugin>
    ...
    <executions>
        <execution>
            <id>output-html</id>              <!--1-->
            <phase>generate-resources</phase> <!--2-->
            <goals>
                <goal>process-asciidoc</goal> <!--3-->
            </goals>
        </execution>
    </executions>
</plugin>
----
<1> 这是执行唯一ID。This is simply an unique id for the execution
<2> asciidoctor-maven-plugin 不在任意环节运行，所以必须指定一个环节。
<3> Asciidoctor Maven 插件在此时的执行目标。

[[configuration-options]]
=== 配置选项

asciidoctor-maven-plugin 有很多配置选项，这些配置在 Asciidoctor 也是可用的：

sourceDirectory:: 默认指向 `${basedir}/src/main/asciidoc`
sourceDocumentName:: an override to process a single source file; 默认指向 `${sourceDirectory}` 中的所有文件
sourceDocumentExtensions:: （在 v1.5.3 及其以下版本中被命名为 `extensions`) 一系列需要渲染的不标准的文件扩展名。目前，ad、adoc 和 asciidoc 默认就会被渲染。
outputDirectory:: 默认指向 `${project.build.directory}/generated-docs`
baseDir:: （不是 Maven 的 basedir）设置资源（例如被包含的文件）的根目录，默认指向 `${sourceDirectory}`。
skip:: 跳过生成则设置为 `true`， 默认`false`。
preserveDirectories:: 指明是否渲染成和源文件相同的目录结构。默认为 `false`。
当为 `true` 时，不在将所有文件都生成到同一个目录中，而是将输出文件生成到相同的目录结构中。看下面的例子。
+
[source]
----
    ├── docs                          ├── docs
    │   ├── examples.adoc             │   ├── examples.html
    │   └── examples            =>    │   └── examples
    │       ├── html.adoc             │       ├── html.html
    │       └── docbook.adoc          │       └── docbook.html
    └── index.adoc                    └── index.html
----
relativeBaseDir:: 只有在 `baseDir` 没有指明的情况下才使用。启用则指明每一个 AsciiDoc 文件都必须从同一个目录下搜索它的资源文件（例如被包含的文件）。在内部，对于每一个 AsciiDoc 源文件，设置 `baseDir` 与源文件相同的路径。默认为 `false`。
imagesDir:: 默认指向 `images`，它是相对于源码目录的相对路径。
backend:: 默认是 `docbook`。
doctype:: 默认为 `null` （它将触发 Asciidoctor 的默认值 `article`）
eruby:: 默认为 erb，被 JRuby 使用
// eruby:: defaults to erb, the version used in JRuby
headerFooter:: 默认为 `true`
templateDir:: 默认不可用，默认值为 `null`
templateEngine:: 默认不可用
sourceHighlighter:: 启用语法高亮，设置语法高亮器（当前仅支持 `coderay` 和 `highlight.js`）
attributes:: 包含传递给 Asciidoctor 的属性的 `Map<String,Object>`，默认为 `null`
embedAssets:: 内嵌的 CSS 文件，指向输出，默认为 `false`
// embedAssets:: Embedd the CSS file, etc into the output, defaults to `false`
gemPaths:: 用于指明一个或多个 gem 安装路径（等同 GEM_PATH 环境变量），默认为 `empty`
requires:: a `List<String>` to specify additional Ruby libraries not packaged in AsciidoctorJ, `empty` by default
extensions:: 被包含进转化过程的扩展列表（可从 link:https://github.com/asciidoctor/asciidoctorj/blob/master/README.adoc#extension-api[AsciidoctorJ's Extension API] 更多可选项的信息）。对于每一个扩展，实现类必须在 `className` 参数中指明，`blockName` 参数只有在配置 _BlockProcessor_， _BlockMacroProcessor_ 或 _InlineMacroProcessor_ 才需要指定。下面是一个配置例子：
+
[source,xml]
----
<plugin>
    ...
    <executions>
        <execution>
            <configuration>
                ...
                <extensions>
                    <extension>
                        <className>org.asciidoctor.maven.SomePreprocessor</className>
                    </extension>
                    <extension>
                        <className>org.asciidoctor.maven.SomeBlockProcessor</className>
                        <blockName>yell</blockName>
                    </extension>
                </extensions>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency> <!--1-->
            <groupId>org.asciidoctor.maven</groupId>
            <artifactId>my-asciidoctor-extensions</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</plugin>
----
<1> 注意：处理器必须被包含在插件的执行类路径中，而不是项目的。

NOTE: 扩展也可以通过 SPI 接口实现整合进来。这种方法就不需要在 `pom.xml` 中作任何配置，查看 link:https://github.com/asciidoctor/asciidoctorj#extension-spi[Extension SPI] 获得更多细节。

[[built-in-attributes]]
==== 内置属性

Asciidoctor 包含了一系列属性。下面是它们的一个列表以及它们的作用。

title:: 一个文档的概要标题。

NOTE: 为了向后兼容性，这个属性还可以在顶级配置项中使用。

很多其他属性可用。在 Asciidoctor 给出一个权威列表之前，你可以在 http://asciidoc.org/userguide.html#X88[属性列表] 中看到更多帮助。

为了利用 Asciidoctor 的其他选项和属性，将来会有更多属性被添加进来。
属性部分的任何设置如果和命名属性配置相冲突，将会被命名属性配置所覆盖。
这些设置都可以在插件部分的 `<configuration>` 部分中改变：

[source,xml]
.插件配置选项
----
<plugin>
    <configuration>
        <sourceDirectory>src/docs/asciidoc</sourceDirectory>
        <outputDirectory>target/docs/asciidoc</outputDirectory>
        <backend>html</backend>
        <doctype>book</doctype>
        <attributes>
            <stylesheet>my-theme.css</stylesheet>
        </attributes>
    </configuration>
</plugin>
----

[[passing-pom-properties]]
==== 传递 POM 属性

可以将在 POM 中定义的属性传递给 Asciidoctor 处理器。下面的例子演示在生成文档中包含 POM artifact 版本号。

这些要在 `configuration` 部分的 `attributes` 小节中，通过创建自定义 AsciiDoc 属性来完成。
AsciiDoc 属性值使用常用的 Maven 方式来定义： `${myMavenProperty}`。

[source,xml]
----
<attributes>
    <project-version>${project.version}</project-version>
</attributes>
----

这个自定义的 AsciiDoc 属性接下来就可以在文档中像如下方式使用：

 The latest version of the project is {project-version}.

[TIP]
====
如果你想使用项目的版本作为文档的修订版，使用如下结构：

 :revnumber: {project-version}

这样，版本号将会出现在输出文档的头部和尾部。
====

[[setting-boolean-values]]
==== 设置布尔值

sciidoctor 中的布尔属性，例如 `sectnums`， `linkcss` 或 `copycss` 可以使用 `true` 值来设置，也可以使用 `false` 来取消设置。

[[examples]]
==== 示例

在 Asciidoctor Maven 插件配置的 `<attributes>` 部分：

[source,xml]
----
<sectnums>true</sectnums>
<linkcss>false</linkcss>
----

在 {uri-examples}[Asciidoctor Maven 示例] 项目中，你可以发现更多信息以及可以直接复制粘贴的示例。

[[command-line-configuration]]
==== 命令行配置

配置选项可以直接在命令行中使用系统属性来设置（但不可删除），如下：

 mvn generate-resources -Dasciidoctor.sourceDirectory=src/docs -Dasciidoctor.outputDirectory=target/docs

所有选项按照这样的命名规范： _`asciidoctor.` + option_name_。

为了属性配置有更高的灵活性，请遵循不同的行为。
// In order to provide a higher degree of flexibility `attributes` configuration follows a different behavior
Attributes defined through the command line are added to the ones already found in the XML configuration.
The result of it is that attributes and other configuration options can be updated if they are added to the command line as attributes.
For example, the following configuration could be modified with the command options as seen below.

[source,xml]
----
<configuration>
    <backend>html5</backend>
    <sourceHighlighter>coderay</sourceHighlighter>
    <attributes>
        <toc>left</toc>
    </attributes>
</configuration>
----

 mvn generate-resources -Dasciidoctor.attributes=toc=right

 mvn generate-resources -Dasciidoctor.attributes="toc=right source-highlighter=highlight.js imagesdir=my_images"

注意在第二种情况，你需要引号把属性设置括起来，其中，`source-highlighter` 是 asciidoctor 的属性值名，用于更新配置。

[[multiple-outputs-for-the-same-file]]
=== 相同文件的多个输出

Maven 可以多次执行 Mojo。
Instead of reinventing the wheel inside the Mojo, we'll push this off to Maven to handle the multiple executions.
An example of this setup is below:

[source,xml,subs=attributes+]
.多个配置输出
----
<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>{release-version}</version>
    <executions>
        <execution>
            <id>output-html</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <sourceHighlighter>coderay</sourceHighlighter>
                <backend>html</backend>
                <attributes>
                    <toc/>
                    <linkcss>false</linkcss>
                </attributes>
            </configuration>
        </execution>
        <execution>
            <id>output-docbook</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>docbook</backend>
                <doctype>book</doctype>
            </configuration>
        </execution>
    </executions>
    <configuration>
        <sourceDirectory>src/main/asciidoc</sourceDirectory>
        <headerFooter>true</headerFooter>
        <imagesDir>../resources/images</imagesDir> <!--1-->
    </configuration>
</plugin>
----
<1> `imagesDir` should be relative to the source directory. It defaults to `images` but in this example the images used in the docs are also used elsewhere in the project.

Any configuration specified outside the executions section is inherited by each execution.
This allows an easier way of defining common configuration options.

[[maven-site-integration]]
== Maven Site Integration

To author your Maven-generated site in AsciiDoc, you must first add a dependency on the Asciidoctor plugin to your maven-site-plugin declaration.

[source,xml,subs=attributes+]
.Maven site integration
-----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-site-plugin</artifactId>
            <version>3.4</version>
            <dependencies>
                <dependency>
                    <groupId>org.asciidoctor</groupId>
                    <artifactId>asciidoctor-maven-plugin</artifactId>
                    <version>{release-version}</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
-----

All of your AsciiDoc-based files should be placed in `src/site/asciidoc` with an extension of `.adoc`.
These files will be rendered into the `target/site` directory.
For example, the file `src/site/asciidoc/usage.adoc` will be rendered into `target/site/usage.html`.

The Asciidoctor base directory (i.e., document root) is configured as `src/site/asciidoc` by default, though this can be overridden.
Also note that AsciiDoc files are converted to embeddable HTML and inserted into the site's page layout.
This disables certain features such as a the sidebar toc.

Make sure you add a `menu` item for each page so you can access it from the site navigation:

[source,xml]
-----
<body>
    ...
    <menu name="User guide">
        <item href="usage.html" name="Usage" />
    </menu>
    ...
</body>
-----

[[configuration]]
=== Configuration

As of version 1.5.3 of the plugin, you can configure Asciidoctor by specifying configuration properties in the plugin declaration, just like with the main plugin goal.
There is one important difference, however.
All the configuration for Asciidoctor in the site integration must be nested inside an `<asciidoc>` element.
This is necessary since the `<configuration>` element is used to configure more than just the Asciidoctor integration.

Here's an example that shows how to set options, attributes and ignore partial AsciiDoc files (i.e., files that begin with an underscore).

[source,xml]
.Maven site integration with Asciidoctor configuration
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-site-plugin</artifactId>
    <version>3.4</version>
    <configuration>
        <asciidoc>
            <templateDirs>
                <dir>src/site/asciidoc/templates</dir>
            </templateDirs>
            <requires>
                <require>asciidoctor-diagram</require>
            </requires>
            <attributes>
                <source-highlighter>coderay</source-highlighter>
                <coderay-css>style</coderay-css>
            </attributes>
        </asciidoc>
        <moduleExcludes>
            <asciidoc>**/_*.adoc</asciidoc>
        </moduleExcludes>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctor-maven-plugin</artifactId>
            <version>1.5.3</version>
        </dependency>
    </dependencies>
</plugin>
----

IMPORTANT: The Asciidoctor base directory (i.e., document root) is configured as `src/site/asciidoc` by default, though this can be overridden using the `baseDir` configuration option.

You'll notice that excludes have been added for certain AsciiDoc files.
This prevents the site integration from processing partial files (i.e., includes) as individual pages.
You can tune this pattern to your liking.
There's currently no way (that we can tell) to configure this automatically.

We've also activated the built-in template converter by specifying a templates directory (i.e., `templatesDir`).
This feature enables you to provide a custom template for converting any node in the tree (e.g., document, section, listing, etc).
Custom templates can be extremely helpful when trying to customize the appearance of your site.

// == Watching for changes

// TODO

// == Zipping output into a bundle

// TODO

// == Previewing generated content in the browser

// TODO

[[hacking]]
== Hacking

Developer setup for hacking on this project isn't very difficult. The requirements are very small:

* Java
* Maven 3

Everything else will be brought in by Maven. This is a typical Maven Java project, nothing special. You should be able to use IntelliJ, Eclipse, or Netbeans
without any issue for hacking on the project.

[[building]]
== Building

Standard Maven build:

 mvn clean install

[[testing]]
== Testing

http://spockframework.org/[Spock] is used for testing the calling of the Mojo. This will be downloaded by Maven. Tests are run simply by:

 mvn clean test

Or any of the other goals which run tests.

NOTE: If I can figure out a good way to setup a Ruby testing environment I'll do that as well, but none exists at this time.

[[tips-tricks]]
== Tips & Tricks

[[generate-your-documentation-in-separate-folders-per-version]]
=== Generate your documentation in separate folders per version

[source, xml]
-----
<configuration>
    ...
    <outputDirectory>target/generated-docs/${project.version}</outputDirectory>
    ...
</configuration>
-----

[[enable-section-numbering]]
=== Enable section numbering

[source, xml]
-----
<configuration>
    ...
    <attributes>
        ...
        <sectnums>true</sectnums>
        ...
    </attributes>
    ...
</configuration>
-----
