= Site integration 3.x.x Migration Guide
:navtitle: 3.x.x Migration Guide
:doxia-compatible-module-name: asciidoctor-converter-doxia-module
:doxia-new-module-name: asciidoctor-parser-doxia-module

The `asciidoctor-maven-plugin` and its Doxia Modules 3.0.0 introduces some breaking changes.
This guide will provide the steps required to update a project currently using 2.x.x version.
For each of the breaking changes, the motivation and new equivalent configuration will be offered.

NOTE: New configuration details are highlighted in *bold*.

== Motivations

Changes in this version have been motivated to provide a new easier to use asciidoctor to build sites with Maven site plugin.
With that goal in mind, the single project that contained both the maven plugin and site integration components has been split into different maven submodules.

The old Doxia module embedded in `asciidocto-maven-plugin` library it's now an independent JAR called `{doxia-compatible-module-name}`, and a new one has been created `{doxia-new-module-name}`.

== Changes

=== Site plugin module renamed

The https://maven.apache.org/doxia/[Doxia] module has been extracted into a separated subproject named `{doxia-compatible-module-name}`.

*Rename the maven-site-plugin dependency from `asciidoctor-maven-plugin` to `{doxia-compatible-module-name}`.*

[source,xml,subs=attributes+]
.new configuration
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-site-plugin</artifactId>
    <version>{maven-site-plugin-version}</version>
    <dependencies>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>{doxia-compatible-module-name}</artifactId>
            <version>{release-version}</version>
        </dependency>
    </dependencies>
</plugin>
----
